name: test_workflow2
on: 
    issues:
        types: [opened, edited, milestoned, closed]
jobs:
    issue-job:
        runs-on: ubuntu-latest
        steps:
            - name: Output command
              run: echo "${{ toJson(github) }}"