name: test_workflow1
on: push
jobs:
    test-job:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: '18'
            - name: Install dependencies
              run: npm ci
            - name: Run lint script
              run: npm lint
            - name: Run tests
              run: npm test
    deploy-job:
        needs: test-job
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: '18'
            - name: Install dependencies
              run: npm ci
            - name: Build project
              run: npm run build
            - name: Deploy project
              run: echo "Deploying.."
            
